apiVersion: apps/v1
kind: Deployment
metadata:
  name: vifdspri-website-deployment
  labels:
    app.kubernetes.io/name: vifdspri-website
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vifdspri-website
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vifdspri-website
    spec:
      containers:
      - name: vifdspri-website-front-public
        image: europe-west9-docker.pkg.dev/vifdspri-website/front-public-repo/front-public-image:latest
        ports:
        - containerPort: 3000
          name: next-server
