apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vifdspri-website-ingress
  annotations:
    kubernetes.io/ingress.class: gce
spec:
  defaultBackend:
    service:
      name: vifdspri-website-service
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vifdspri-website-service
            port:
              number: 80